/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "SensorMessages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ConfigClockTask, ConfigClockTask, 2)


PB_BIND(ConfigVibraWireParameter, ConfigVibraWireParameter, AUTO)


PB_BIND(TopInfoNodeData, TopInfoNodeData, 2)


PB_BIND(ClockTaskTimeInfoSensorNode, ClockTaskTimeInfoSensorNode, AUTO)


PB_BIND(ClockTaskSampleInfo, ClockTaskSampleInfo, AUTO)


PB_BIND(VibraWireInfo, VibraWireInfo, AUTO)


PB_BIND(VibraWireData, VibraWireData, AUTO)


PB_BIND(SystemBootInfo, SystemBootInfo, 2)




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

