/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "SensorDownMessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SensorMessages_SensorDownMessage, SensorMessages_SensorDownMessage, 2)



