/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.3 */

#ifndef PB_SENSORMESSAGES_SENSORUPMESSAGE_PB_H_INCLUDED
#define PB_SENSORMESSAGES_SENSORUPMESSAGE_PB_H_INCLUDED
#include "pb.h"
#include "SensorMessages.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorMessages_SensorUpMessage {
    char packet_name[40];
    char node_id[6];
    char gateway_id[16];
    uint32_t unix_time;
    char channel[3];
    pb_size_t which_msg;
    union {
        VibraWireData vibrawiredata;
        TopInfoNodeData topinfonodedata;
        ClockTaskTimeInfoSensorNode clocktasktimeinfosensornode;
        ClockTaskSampleInfo clocktasksampleinfo;
        SystemBootInfo systembootinfo;
        VibraWireInfo vibrawireinfo;
    } msg;
} SensorMessages_SensorUpMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorMessages_SensorUpMessage_init_default {"", "", "", 0, "", 0, {VibraWireData_init_default}}
#define SensorMessages_SensorUpMessage_init_zero {"", "", "", 0, "", 0, {VibraWireData_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SensorMessages_SensorUpMessage_packet_name_tag 1
#define SensorMessages_SensorUpMessage_node_id_tag 2
#define SensorMessages_SensorUpMessage_gateway_id_tag 3
#define SensorMessages_SensorUpMessage_unix_time_tag 4
#define SensorMessages_SensorUpMessage_channel_tag 5
#define SensorMessages_SensorUpMessage_vibrawiredata_tag 22
#define SensorMessages_SensorUpMessage_topinfonodedata_tag 39
#define SensorMessages_SensorUpMessage_clocktasktimeinfosensornode_tag 43
#define SensorMessages_SensorUpMessage_clocktasksampleinfo_tag 55
#define SensorMessages_SensorUpMessage_systembootinfo_tag 99
#define SensorMessages_SensorUpMessage_vibrawireinfo_tag 106

/* Struct field encoding specification for nanopb */
#define SensorMessages_SensorUpMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   packet_name,       1) \
X(a, STATIC,   SINGULAR, STRING,   node_id,           2) \
X(a, STATIC,   SINGULAR, STRING,   gateway_id,        3) \
X(a, STATIC,   SINGULAR, UINT32,   unix_time,         4) \
X(a, STATIC,   SINGULAR, STRING,   channel,           5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,vibrawiredata,msg.vibrawiredata),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,topinfonodedata,msg.topinfonodedata),  39) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,clocktasktimeinfosensornode,msg.clocktasktimeinfosensornode),  43) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,clocktasksampleinfo,msg.clocktasksampleinfo),  55) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,systembootinfo,msg.systembootinfo),  99) \
X(a, STATIC,   ONEOF,    MESSAGE,  (msg,vibrawireinfo,msg.vibrawireinfo), 106)
#define SensorMessages_SensorUpMessage_CALLBACK NULL
#define SensorMessages_SensorUpMessage_DEFAULT NULL
#define SensorMessages_SensorUpMessage_msg_vibrawiredata_MSGTYPE VibraWireData
#define SensorMessages_SensorUpMessage_msg_topinfonodedata_MSGTYPE TopInfoNodeData
#define SensorMessages_SensorUpMessage_msg_clocktasktimeinfosensornode_MSGTYPE ClockTaskTimeInfoSensorNode
#define SensorMessages_SensorUpMessage_msg_clocktasksampleinfo_MSGTYPE ClockTaskSampleInfo
#define SensorMessages_SensorUpMessage_msg_systembootinfo_MSGTYPE SystemBootInfo
#define SensorMessages_SensorUpMessage_msg_vibrawireinfo_MSGTYPE VibraWireInfo

extern const pb_msgdesc_t SensorMessages_SensorUpMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorMessages_SensorUpMessage_fields &SensorMessages_SensorUpMessage_msg

/* Maximum encoded size of messages (where known) */
#define SensorMessages_SensorUpMessage_size      280

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
